"""Add Subject and GenerationTask models with status tracking

Revision ID: 682f2c06daff
Revises: 65dd2ee5a878
Create Date: 2026-02-10 19:44:25.278616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682f2c06daff'
down_revision: Union[str, None] = '65dd2ee5a878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create ENUM types first
    contentstatus = sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='contentstatus')
    contentstatus.create(op.get_bind(), checkfirst=True)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grade_level', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standards', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'GENERATING', 'DRAFT', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'REJECTED', name='subjectstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('generation_task_id', sa.String(length=100), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('total_domains', sa.Integer(), nullable=True),
    sa.Column('total_topics', sa.Integer(), nullable=True),
    sa.Column('total_lessons', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_status'), 'subjects', ['status'], unique=False)
    op.create_table('generation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.Enum('CURRICULUM_GENERATION', 'LESSON_GENERATION', 'EXERCISE_GENERATION', 'TRANSLATION_GENERATION', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_tasks_id'), 'generation_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_generation_tasks_status'), 'generation_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_generation_tasks_task_id'), 'generation_tasks', ['task_id'], unique=True)

    op.add_column('domains', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('domains', sa.Column('status', contentstatus, server_default='DRAFT', nullable=False))
    op.add_column('domains', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('domains', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('domains', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_domains_status'), 'domains', ['status'], unique=False)
    op.create_foreign_key(None, 'domains', 'users', ['reviewed_by'], ['id'])
    op.create_foreign_key(None, 'domains', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'domains', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domains', type_='foreignkey')
    op.drop_constraint(None, 'domains', type_='foreignkey')
    op.drop_constraint(None, 'domains', type_='foreignkey')
    op.drop_index(op.f('ix_domains_status'), table_name='domains')
    op.drop_column('domains', 'reviewed_at')
    op.drop_column('domains', 'reviewed_by')
    op.drop_column('domains', 'created_by')
    op.drop_column('domains', 'status')
    op.drop_column('domains', 'subject_id')
    op.drop_index(op.f('ix_generation_tasks_task_id'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_status'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_id'), table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index(op.f('ix_subjects_status'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
