'use client'

import { motion } from 'framer-motion'
import {
  SparklesIcon,
  GlobeAltIcon,
  ChartBarIcon,
  LightBulbIcon,
  ShieldCheckIcon,
  BoltIcon,
  UserGroupIcon,
  DevicePhoneMobileIcon
} from '@heroicons/react/24/outline'

const features = [
  {
    icon: SparklesIcon,
    title: 'AI-Powered Content',
    description: 'Lessons generated by Claude Opus 4.6, ensuring high-quality, accurate, and engaging educational content.',
    color: 'from-blue-500 to-indigo-600'
  },
  {
    icon: GlobeAltIcon,
    title: 'Multi-Language Support',
    description: 'Learn in your native language. Currently supporting English, Tamil, with more languages coming soon.',
    color: 'from-indigo-500 to-purple-600'
  },
  {
    icon: ChartBarIcon,
    title: 'Progress Tracking',
    description: 'Real-time analytics showing your learning journey, streaks, completion rates, and areas for improvement.',
    color: 'from-purple-500 to-pink-600'
  },
  {
    icon: LightBulbIcon,
    title: 'Adaptive Learning',
    description: 'Content difficulty adjusts to your pace. Get personalized recommendations based on your performance.',
    color: 'from-pink-500 to-rose-600'
  },
  {
    icon: ShieldCheckIcon,
    title: 'GDPR & COPPA Compliant',
    description: 'Your data is secure. We follow strict privacy standards and never share your personal information.',
    color: 'from-green-500 to-emerald-600'
  },
  {
    icon: BoltIcon,
    title: 'Lightning Fast',
    description: 'Optimized for performance with <2.5s page loads. Learn without waiting, on any device.',
    color: 'from-yellow-500 to-orange-600'
  },
  {
    icon: UserGroupIcon,
    title: 'For Everyone',
    description: 'From students to professionals, learners to educators. Free forever with optional premium features.',
    color: 'from-cyan-500 to-blue-600'
  },
  {
    icon: DevicePhoneMobileIcon,
    title: 'Fully Responsive',
    description: 'Seamless experience on desktop, tablet, and mobile. Learn anywhere, anytime, on any device.',
    color: 'from-teal-500 to-cyan-600'
  }
]

export default function FeaturesSection() {
  return (
    <section className="py-24 bg-white dark:bg-gray-900">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="max-w-3xl mx-auto text-center mb-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-4xl sm:text-5xl font-bold text-gray-900 dark:text-white mb-4">
              Why Choose <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">LearningHub</span>
            </h2>
            <p className="text-xl text-gray-600 dark:text-gray-300">
              Built with cutting-edge technology to provide the best learning experience
            </p>
          </motion.div>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              whileHover={{ y: -8, transition: { duration: 0.2 } }}
              className="group"
            >
              <div className="relative h-full bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-800 dark:to-gray-900 rounded-2xl p-8 border border-gray-200 dark:border-gray-800 hover:border-blue-500 dark:hover:border-blue-500 transition-all duration-300 shadow-lg hover:shadow-xl">
                {/* Icon */}
                <div className={`inline-flex items-center justify-center w-14 h-14 bg-gradient-to-br ${feature.color} rounded-xl mb-6 shadow-lg`}>
                  <feature.icon className="w-7 h-7 text-white" />
                </div>

                {/* Content */}
                <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                  {feature.description}
                </p>

                {/* Hover effect - gradient border glow */}
                <div className={`absolute inset-0 bg-gradient-to-br ${feature.color} opacity-0 group-hover:opacity-10 rounded-2xl transition-opacity duration-300`} />
              </div>
            </motion.div>
          ))}
        </div>

        {/* Bottom CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="mt-16 text-center"
        >
          <p className="text-lg text-gray-600 dark:text-gray-300 mb-6">
            Join thousands of learners already mastering new skills
          </p>
          <div className="flex flex-wrap gap-4 justify-center items-center">
            <div className="flex items-center gap-2 px-4 py-2 bg-green-100 dark:bg-green-900/30 rounded-lg">
              <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
              <span className="text-sm font-medium text-green-700 dark:text-green-400">
                100K+ Active Learners
              </span>
            </div>
            <div className="flex items-center gap-2 px-4 py-2 bg-blue-100 dark:bg-blue-900/30 rounded-lg">
              <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />
              <span className="text-sm font-medium text-blue-700 dark:text-blue-400">
                2,500+ Lessons
              </span>
            </div>
            <div className="flex items-center gap-2 px-4 py-2 bg-purple-100 dark:bg-purple-900/30 rounded-lg">
              <div className="w-2 h-2 bg-purple-500 rounded-full animate-pulse" />
              <span className="text-sm font-medium text-purple-700 dark:text-purple-400">
                99.9% Uptime
              </span>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  )
}
